### PR TITLE
issue: 1027659: Fix cqe timestamp conversion - prm poll cq implementa…

### PR DESCRIPTION
**Pull request by DanielLibenson**
…tion

Added ntohll conversion for hw cqe timestamp value.

Signed-off-by: Daniel Libenson <danielli@mellanox.com>

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/1666/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1104/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/1668/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1106/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/1670/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1108/ for details (Mellanox internal link).

**Comment by ilansmith** [comment]
:+1:

**Comment by OphirMunk** [comment]
:+1:

**Comment by ilansmith** [comment]
#360 has been merged.

**Pull request closed without merging**
