### PR TITLE
issue: 800923 Remove and ignore autoconf files

### PR DESCRIPTION
**Pull request by igor-ivanov**
No need in config.guess and config.sub files after moving to
autoconf 2.69 because support for the ARM 64 bit CPU architecture
(aarch64) was introduced in autoconf 2.69.

Signed-off-by: Igor Ivanov <igor.ivanov.va@gmail.com>

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-redmine-issue/57/ for details (Mellanox internal link).

**Comment by miked-mellanox** [comment]
need to use ``` AC_PREREQ([2.69]) ``` in Makefile.am

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/174/ for details (Mellanox internal link).

**Comment by rosenbaumalex** [comment]
@igor-ivanov since which RHEL and Ubuntu distro releases is 'autoconf 2.69' available?
we need to understand what support are we dropping behind with this change.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-redmine-issue/58/ for details (Mellanox internal link).

**Comment by igor-ivanov** [comment]
@rosenbaumalex formally we moved to autoconf 2.69 in following commit https://github.com/Mellanox/libvma/commit/79a6c3. Current commit just completes this moving.
Do we have open requirements to supported version?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/175/ for details (Mellanox internal link).

**Comment by OphirMunk** [comment]
@igor-ivanov did you try building under ARM 64 architecture with this PR?

**Comment by igor-ivanov** [comment]
bot:retest

**Comment by igor-ivanov** [comment]
@OphirMunk I have not found ARM64 to check.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-redmine-issue/61/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/178/ for details (Mellanox internal link).

**Comment by igor-ivanov** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-redmine-issue/63/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/180/ for details (Mellanox internal link).

**Comment by OphirMunk** [comment]
@igor-ivanov sent in email IP address of an ARM64 machine

**Comment by OphirMunk** [comment]
Build confirmed by Igor on ARM64 machine
:+1:

**Comment by OphirMunk** [comment]
PR reverted due to build failure on some machines

**Pull request merged**
