### PR TITLE
issue: 1043382 Fix VMA_PROGRESS_ENGINE_WCE_MAX incorrect value in REA…

### PR DESCRIPTION
**Pull request by liranoz12**
…DME.txt

Update VMA_PROGRESS_ENGINE_WCE_MAX value from 2048 to 10000

Signed-off-by: Liran Oz <lirano@mellanox.com>

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/1768/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1213/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/1770/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1215/ for details (Mellanox internal link).

**Comment by OphirMunk** [comment]
Merged #318

**Pull request closed without merging**
