### PR TITLE
issue: 854219 Systemize m_p_rx_ring update flow

### PR DESCRIPTION
**Pull request by igor-ivanov**
m_p_rx_ring should be updated in following functions:
  - rx_add_ring_cb()
  - rx_del_ring_cb()
  - do_rings_migration()

@OphirMunk @alexvm @rosenbaumalex please look at and accept

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/517/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/530/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/532/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/519/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/520/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/521/ for details (Mellanox internal link).

**Comment by OphirMunk** [comment]
Merge #220

**Pull request closed without merging**
