### PR TITLE
issue: 1031334 Fix for regression with recvmsg IP_PKRINFO

### PR DESCRIPTION
**Pull request by olgk**
Regression with recvmsg IP_PKTINFO was fixed in fast
data path for FlowTag by filling full L3 and L4 sockaddr_in.

Signed-off-by: Oleg Kuporosov <olegk@mellanox.com>

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/1763/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1208/ for details (Mellanox internal link).

**Comment by olgk** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/1765/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1210/ for details (Mellanox internal link).

**Comment by ilansmith** [comment]
bot:retest

**Comment by ilansmith** [comment]
:+1:

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/1773/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1218/ for details (Mellanox internal link).

**Comment by olgk** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/1774/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1219/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1220/ for details (Mellanox internal link).

**Comment by ilansmith** [comment]
Hi Ophir,

I've reviewed this (the PR is here<https://github.com/Mellanox/libvma/pull/380>), it's passed Jenkins and is ready for master as we discussed during the daily meeting.

Do you want to take a look before I push it?

My only comments are about code repetition, but in fact, the entire function ring_simple:: rx_process_buffer() suffers from code reuse and needs to be refactored.
Per my request, Oleg is opening a separate RM issue for doing this.

I'll be changing the commit message to be:

Author: Oleg Kuporosov <olegk@mellanox.com>
Date:   Fri May 12 16:30:39 2017 +0000

    issue: 1031334 Fix missing src/dst info for IP_PKTINFO setsockopt

    Fill L3 and L4 family, src/dst and port information in the buffer
    descriptor's sockaddr_in when using flowtag.

    Signed-off-by: Oleg Kuporosov <olegk@mellanox.com>


-          Ilan

**Comment by ilansmith** [comment]
Merged #380.

**Pull request closed without merging**
