### PR TITLE
issue: 1172298 Rename jenkins traget vmapoll with socketxtreme

### PR DESCRIPTION
**Pull request by igor-ivanov**
Signed-off-by: Igor Ivanov <igor.ivanov.va@gmail.com>

### CODE REVIEW

**Comment by liranoz12** [comment]
Please also rename the following:
https://github.com/Mellanox/libvma/blob/master/tests/gtest/README#L10

What about gtest file ? do we want to rename them too ?
https://github.com/Mellanox/libvma/blob/master/tests/gtest/vma/vma_ring.cc
https://github.com/Mellanox/libvma/blob/master/tests/gtest/vma/vma_poll.cc

**Comment by igor-ivanov** [comment]
> Please also rename the following:
https://github.com/Mellanox/libvma/blob/master/tests/gtest/README#L10

done

>What about gtest file ? do we want to rename them too ?
https://github.com/Mellanox/libvma/blob/master/tests/gtest/vma/vma_ring.cc
https://github.com/Mellanox/libvma/blob/master/tests/gtest/vma/vma_poll.cc

no need

**Comment by liranoz12** [comment]
bot:retest

**Comment by liranoz12** [comment]
bot:retest

**Pull request merged**
