### PR TITLE
issue: 1131365 Fix VMA README.txt file

### PR DESCRIPTION
**Pull request by DanielLibenson**
Fix VMA output example and update default parameters.

Signed-off-by: Daniel Libenson <danielli@mellanox.com>

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1636/ for details (Mellanox internal link).

**Comment by DanielLibenson** [comment]
bot:retest

**Comment by rafiw** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1637/ for details (Mellanox internal link).

**Comment by DanielLibenson** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1640/ for details (Mellanox internal link).

**Comment by liranoz12** [comment]
Merged #461

**Pull request closed without merging**
