### PR TITLE
issue: 825888 Fix incorrect TCP snd_wnd statistic

### PR DESCRIPTION
**Pull request by igor-ivanov**
Signed-off-by: Igor Ivanov <igor.ivanov.va@gmail.com>

### CODE REVIEW

**Comment by liranoz12** [comment]
bot:retest

**Comment by liranoz12** [comment]
I dont think this is the right solution.
pcb->snd_wnd should contain the scaled window.
We need to shift the value to the opposite way.
Something like : 
pcb.snd_wnd >> pcb.snd_scale.

src/vma/lwip/tcp.c:594:  pcb->snd_wnd = TCP_WND;
src/vma/lwip/tcp_in.c:377:    npcb->snd_wnd = in_data->tcphdr->wnd;
src/vma/lwip/tcp_in.c:401:      npcb->snd_wnd = SND_WND_SCALE(npcb, in_data->tcphdr->wnd);
src/vma/lwip/tcp_in.c:544:      pcb->snd_wnd = SND_WND_SCALE(pcb, in_data->tcphdr->wnd);
src/vma/lwip/tcp_in.c:776:       pcb->snd_wnd = SND_WND_SCALE(pcb, in_data->tcphdr->wnd);

**Comment by igor-ivanov** [comment]
you are right

**Comment by liranoz12** [comment]
:+1:

**Pull request merged**
