### PR TITLE
Flow tag - based of #315

### PR DESCRIPTION
**Pull request by ilansmith**
Changes compared to #315:
- Rebased
- Changed commit messages and README.txt

Issuing for a sanity Jenkins run.
No other changes as compared to #315, hence regression on vNext is not required.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/1348/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/902/ for details (Mellanox internal link).

**Comment by ilansmith** [comment]
Was used for running a Jenkins sanity test. Closing.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/1369/ for details (Mellanox internal link).

**Pull request closed without merging**
