### PR TITLE
comment out coverity scan results from README.md

### PR DESCRIPTION
**Pull request by rosenbaumalex**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/1797/ for details (Mellanox internal link).

**Comment by OphirMunk** [comment]
@rosenbaumalex please find a suggested title (just confirm. No need to new push)

issue: 847360 Update github's README.md file

Remove Coverity badge

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1245/ for details (Mellanox internal link).

**Comment by OphirMunk** [comment]
Merged #392

**Pull request closed without merging**
