### PR TITLE
issue: 1392812 Fix Bad release of UMR resources

### PR DESCRIPTION
**Pull request by rafiw**
Signed-off-by: Rafi Wiener <rafiw@mellanox.com>

### CODE REVIEW

**Comment by liranoz12** [comment]
bot:retest

**Comment by liranoz12** [comment]
Please resolve the conflicts @rafiw

**Comment by liranoz12** [comment]
bot:retest

**Comment by igor-ivanov** [comment]
this PR is covered by https://github.com/Mellanox/libvma/pull/628

**Comment by rafiw** [comment]
fixed in #628

**Pull request closed without merging**
