### PR TITLE
issue: 1521396 Fix user memory passing to socket

### PR DESCRIPTION
**Pull request by rafiw**
Signed-off-by: Rafi Wiener <rafiw@mellanox.com>

### CODE REVIEW

**Comment by liranoz12** [comment]
bot:retest

**Comment by rafiw** [comment]
bot:retest

**Comment by liranoz12** [comment]
bot:retest

**Comment by liranoz12** [comment]
@rafiw , please remove redundant assignment :
https://github.com/Mellanox/libvma/blob/master/src/vma/dev/allocator.cpp#L98

**Pull request merged**
