### PR TITLE
issue: 1190638 align lwip timer interval to VMA tcp timer interval

### PR DESCRIPTION
**Pull request by rafiw**
Signed-off-by: Rafi Wiener <rafiw@mellanox.com>

### CODE REVIEW

**Comment by MrBr-github** [comment]
bot:retest

**Comment by MrBr-github** [comment]
bot:retest

**Comment by liranoz12** [comment]
There are still three occurrences of the parameters you have removed - two of them are part of the documentation.

```
[lirano@r-aa-apollo03 13:15:28 libvma](git::pr_502_orig)$ grep -nir "TCP_SLOW_INTERVAL\|TCP_FAST_INTERVAL\|TCP_TMR_INTERVAL" src
src/vma/lwip/tcp.c:921: * Is called every TCP_FAST_INTERVAL (250 ms) and process data previously
src/vma/lwip/tcp_impl.h:50:                                         TCP_TMR_INTERVAL
src/vma/lwip/tcp_in.c:994:                                  m, m * TCP_SLOW_INTERVAL));
```
documentation should be updated also here :
```
src/vma/lwip/tcp.c:147:  /* Call tcp_fasttmr() every 100 ms */
src/vma/lwip/tcp.c:151:    /* Call tcp_tmr() every 200 ms, i.e., every other timer
src/vma/lwip/tcp.c:699: * Called every 500 ms and implements the retransmission timer and the timer that
src/vma/lwip/tcp.c:921: * Is called every TCP_FAST_INTERVAL (250 ms) and process data previously
src/vma/lwip/tcp_impl.h:51:                                         ms. (Typically 250 ms). */
```

**Comment by liranoz12** [comment]
:+1:

**Pull request merged**
