### PR TITLE
issue: 1065276 Fix incorrect logging strings

### PR DESCRIPTION
**Pull request by liranoz12**
Signed-off-by: Liran Oz <lirano@mellanox.com>

### CODE REVIEW

**Comment by liranoz12** [comment]
@olgk Please review

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1409/ for details (Mellanox internal link).

**Comment by olgk** [comment]
+1

**Comment by liranoz12** [comment]
Merged. #420

**Pull request closed without merging**
