### PR TITLE
issue: 848239 Remove unused utility functions

### PR DESCRIPTION
**Pull request by rosenbaumalex**
Signed-off-by: Alex Rosenbaum <Alexr@mellanox.com>

### CODE REVIEW

**Comment by rosenbaumalex** [comment]
note that this commit also clears a coverity issue found in one of the unused functions

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/395/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/412/ for details (Mellanox internal link).

**Comment by OphirMunk** [comment]
:+1:

**Comment by Di0gen** [comment]
bot:retest

**Comment by Di0gen** [comment]
bot:retest

**Comment by Di0gen** [comment]
bot:retest

**Comment by Di0gen** [comment]
bot:retest

**Pull request merged**
