### PR TITLE
issue: 798291 Fix compilation issue for gcc

### PR DESCRIPTION
**Pull request by igor-ivanov**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-redmine-issue/38/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/155/ for details (Mellanox internal link).

**Comment by OphirMunk** [comment]
+1
@igor-ivanov  Do you want to fix Jenkins compilations before merge?

**Comment by OphirMunk** [comment]
@igor-ivanov Do you want to fix Jenkins errors before merge?

**Comment by OphirMunk** [comment]
Merge is pending Jenkins errors check. 
Merge will be in conjunction with PR #112

**Comment by igor-ivanov** [comment]
@OphirMunk, @alexvm it can be merged

**Pull request merged**
