### PR TITLE
issue: 788404 Add Packet Pacing support (socket option SO_MAX_PACING_…

### PR DESCRIPTION
**Pull request by OphirMunk**
…RATE)

Signed-off-by: Ophir Munk <ophirmu@mellanox.com>

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/738/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/798/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/740/ for details (Mellanox internal link).

**Comment by ilansmith** [comment]
Replaced by #399.

**Pull request closed without merging**
