### PR TITLE
issue: 874152 Add wc error processing

### PR DESCRIPTION
**Pull request by igor-ivanov**
@alexvm @OphirMunk please review

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/548/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/540/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/541/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/549/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/550/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/542/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/545/ for details (Mellanox internal link).

**Comment by igor-ivanov** [comment]
one commit was moved to PR https://github.com/Mellanox/libvma/pull/225

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/552/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/554/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/547/ for details (Mellanox internal link).

**Comment by OphirMunk** [comment]
@igor-ivanov Please find initial review in attached PATCH file
[0001-Ophir-review-12-Oct-16.txt](https://github.com/Mellanox/libvma/files/525444/0001-Ophir-review-12-Oct-16.txt)

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/552/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/559/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/560/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/553/ for details (Mellanox internal link).

**Comment by igor-ivanov** [comment]
Performance measurements:

<pre>
env VMA_RX_POLL=-1 LD_PRELOAD=libvma.so sockperf sr -i x.x.x.x -m256 --tcp --vmapoll
env VMA_RX_POLL=-1 LD_PRELOAD=libvma.so sockperf pp -i x.x.x.x -m256 --tcp --vmapoll -t10
</pre>


fe885f7 | c6fd2b5 | 9303fa8 | 300de75 | 07da18a
---------|----------|----------|-----------|----------
3.913 | 4.016 | 3.875 | 3.992 | 3.882
3.892 | 3.968 | 3.872 | 3.992 | 3.876
3.907 | 4.023 | 3.863 | 3.994 | 3.871

**Comment by OphirMunk** [comment]
@alexvm Please look at @igor-ivanov performance measurements and notice that V1 commit (3rd column) is not worse than V3 commit (5th column). We need to review and understand it.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/557/ for details (Mellanox internal link).

**Comment by igor-ivanov** [comment]
Performance measurements with b3cf210:

<pre>
env VMA_RX_POLL=-1 LD_PRELOAD=libvma.so sockperf sr -i x.x.x.x -m256 --tcp --vmapoll
env VMA_RX_POLL=-1 LD_PRELOAD=libvma.so sockperf pp -i x.x.x.x -m256 --tcp --vmapoll -t10
</pre>

fe885f7 | c6fd2b5 | 9303fa8 | 300de75 | 07da18a | b3cf210
---------|----------|----------|-----------|----------|----------
3.422 | 3.506 | 3.381 | 3.493 | 3.384 | 3.372
3.427 | 3.518 | 3.378 | 3.498 | 3.372 | 3.365
3.413 | 3.498 | 3.380 | 3.506 | 3.382 | 3.364

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/564/ for details (Mellanox internal link).

**Comment by OphirMunk** [comment]
@igor-ivanov compilation fails on gcc version 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC)
Why Jenkins did not catch?

```
cc1plus: warnings being treated as errors
dev/cq_mgr.h: In constructor ?cq_mgr::cq_mgr(ring_simple*, ib_ctx_handler*, int, ibv_comp_channel*, bool)?:
dev/cq_mgr.h:174: error: ?cq_mgr::m_b_is_rx? will be initialized after
dev/cq_mgr.h:169: error:   ?const uint32_t cq_mgr::m_n_sysvar_rx_num_wr_to_post_recv?
dev/cq_mgr.cpp:154: error:   when initialized here
make[5]: *** [dev/cq_mgr.lo] Error 1
```

**Comment by OphirMunk** [comment]
@igor-ivanov regarding latest performance measurements: it is good to realize that the final commit has the best performance

**Comment by igor-ivanov** [comment]
changes were pushed to the branch

**Pull request closed without merging**
