### PR TITLE
issue: 850270 Add new low latency spec - MCE_SPEC_LL_6973

### PR DESCRIPTION
**Pull request by DanielLibenson**
Signed-off-by: Daniel Libenson <daneilli@mellanox.com>

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/461/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/476/ for details (Mellanox internal link).

**Comment by DanielLibenson** [comment]
boot:retest

**Comment by DanielLibenson** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/462/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/478/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/479/ for details (Mellanox internal link).

**Comment by OphirMunk** [comment]
@DanielLibenson Please update main.cpp as well (was skipped)

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/463/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/480/ for details (Mellanox internal link).

**Comment by OphirMunk** [comment]
Merged #206

**Pull request closed without merging**
