### PR TITLE
issue: 825842 Fix compilation errors while enabling LWIP debug options

### PR DESCRIPTION
**Pull request by liranoz12**
Signed-off-by: Liran Oz <lirano@mellanox.com>

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/210/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/223/ for details (Mellanox internal link).

**Comment by rosenbaumalex** [comment]
+1

**Comment by igor-ivanov** [comment]
:+1:

**Pull request merged**
