### PR TITLE
issue: 2436876 Add C++11 Support requirement to a compiler

### PR DESCRIPTION
**Pull request by igor-ivanov**
Signed-off-by: Igor Ivanov <igor.ivanov.va@gmail.com>

### CODE REVIEW

**Review by SimonRaviv — COMMENTED** [review]
1. I didn't see that you have added -std=c++11 to the compilation flags. Why ?
2. Don't we want to replace tr1 namespace with std namespace ?

**Comment by igor-ivanov** [comment]
> 1. I didn't see that you have added -std=c++11 to the compilation flags. Why ?
> 2. Don't we want to replace tr1 namespace with std namespace ?

It is done by `CHECK_COMPILER_CXX([11], [std], [])`

**Comment by SimonRaviv** [comment]
> > 1. I didn't see that you have added -std=c++11 to the compilation flags. Why ?
> > 2. Don't we want to replace tr1 namespace with std namespace ?
> 
> 1. It is done by `CHECK_COMPILER_CXX([11], [std], [])`
> 2. What is an advantage? In any case it could be done in additional commits.

1. Is it just a check or you set it ? because not setting -std=c++11 as a flag and the default, is not the same.
2. The advantage is not using deprecated staff, and using the std. It shouldn't be too hard to change. We can do it in a different commit.

**Comment by igor-ivanov** [comment]
> > > 1. I didn't see that you have added -std=c++11 to the compilation flags. Why ?

CHECK_COMPILER_CXX([11], [std], []) checks if c++11 can be used and set `-std=c+11` or report error
Line is 
https://github.com/Mellanox/libvma/pull/933/files#diff-703b919299ea9c0c668b27e324458305a3218b82c7c2bc4f9b4868e4fed9c28cR116

**Review by pasis — APPROVED** [review]

**Comment by igor-ivanov** [comment]
Moved to master as a part of PR https://github.com/Mellanox/libvma/pull/971

**Pull request closed without merging**
