### PR TITLE
issue: 786030 revise RDTSC logic to consider CPU speeds taken from /proc/cpuinfo

### PR DESCRIPTION
**Pull request by rosenbaumalex**
1. Read the CPU's Hz (based on /proc/cpuinfo Mhz report)
2. Provide the MAX and MIN values, which might be the case if core are
running at power control states
3. Report CPu speed on libvma bringup
4. Update time_measurements_test

Signed-off-by: Alex Rosenbaum <Alexr@mellanox.com>

### CODE REVIEW

**Comment by rosenbaumalex** [comment]
a 'side effect' of this commit removes the potential blocking in 'usleep(1000)' call form get_tcs_rate_per_second().
1. Increase accuracy in the calibrate RDTSC with CPU speed - new logic is not disturbed by system context switches
2. This resolves coverify issue: "Program Hangs"

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/305/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/323/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/315/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/333/ for details (Mellanox internal link).

**Comment by rosenbaumalex** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/316/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/334/ for details (Mellanox internal link).

**Comment by rosenbaumalex** [comment]
putting on hold

**Pull request closed without merging**
