### PR TITLE
new route architecture : netlink changes

### PR DESCRIPTION
**Pull request by ashanably**
Signed-off-by: ashanably ashanably@asaltech.com

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/555/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/548/ for details (Mellanox internal link).

**Comment by ilansmith** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/556/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/563/ for details (Mellanox internal link).

**Comment by liranoz12** [comment]
PR was closed because advanced_routing brunch was moved to libvma-internal repository.

**Pull request closed without merging**
