### PR TITLE
issue: 899878 BUILD file was renamed to BUILD.txt

### PR DESCRIPTION
**Pull request by olgk**
cross-naming issue with build folder on filesystems which doesn't
distinguish letter cases (NTFS, FATs, etc). Is is applicable when you have
to use Windows as remote station for fast code analysis in IDE locally
as remote access is pretty slow sometimes.

Signed-off-by: Oleg Kuporosov <olegk@mellanox.com>

### CODE REVIEW

**Comment by olgk** [comment]
@OphirMunk @NirNitzani , please review and if OK, please include into 8.2

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/637/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/632/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/633/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/638/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/639/ for details (Mellanox internal link).

**Comment by OphirMunk** [comment]
@olgk Please rename file as BUILD.txt
Please remove old file and create the next file as part of the commit

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/655/ for details (Mellanox internal link).

**Comment by ilansmith** [comment]
@olgk, please address ASAP so we can close this.

**Comment by igor-ivanov** [comment]
@olgk I would like to propose moving **BUILD** folder to **contrib/dist**.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/661/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/653/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/662/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/654/ for details (Mellanox internal link).

**Comment by olgk** [comment]
@OphirMunk , BUILD was renamed to BUILD.txt per your request.

**Comment by OphirMunk** [comment]
On Igor comment: I would like to propose moving BUILD folder to contrib/dist.
@igor-ivanov you may suggest this as a PR for next release

**Comment by OphirMunk** [comment]
Merged #250

**Pull request closed without merging**
