### PR TITLE
issue: 781492 Add VMA zcopy API support to testbed

### PR DESCRIPTION
**Pull request by igor-ivanov**
This commit consists of:
- Add read/write non-blocking support. It can be controlled
by BLOCKING_READ_ENABLED=[0|1] and BLOCKING_WRITE_ENABLED=[0|1]
- Fix several bugs
- Add mlock/munlock for statistic memory region

@alexvm could you look at

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-redmine-issue/37/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/154/ for details (Mellanox internal link).

**Comment by OphirMunk** [comment]
@igor-ivanov  following a review with alexv - do you need to update this PR before merge?

**Comment by OphirMunk** [comment]
Merge is pending updates following a review with AlexV

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-redmine-issue/43/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/160/ for details (Mellanox internal link).

**Comment by igor-ivanov** [comment]
@OphirMunk, @alexvm it can be merged

**Pull request merged**
