### PR TITLE
issue: 1049980 Fix coverity-8.7 failures

### PR DESCRIPTION
**Pull request by igor-ivanov**
These changes suppress issues reported by coverity-8.7 because
it is not clear at the moment if it is actual issue or not.
Additional investigation should e done later.

Signed-off-by: Igor Ivanov <igor.ivanov.va@gmail.com>

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1462/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1467/ for details (Mellanox internal link).

**Comment by OphirMunk** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1475/ for details (Mellanox internal link).

**Comment by OphirMunk** [comment]
Merged #429

**Pull request closed without merging**
