### PR TITLE
issue: 849421 Updated udp_lat test for vma_poll udp

### PR DESCRIPTION
**Pull request by serglelv**
Updated udp_lat test application with vma_poll enabled functionality from libvma-internal. 
@igor-ivanov @OphirMunk 
Signed-off-by: Sergey Lykov sergeyly@mellanox.com

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/459/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/474/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/1130/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/839/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1441/ for details (Mellanox internal link).

**Comment by liranoz12** [comment]
PR was closed because experimental_256B was moved to libvma-internal repository.

**Pull request closed without merging**
