### PR TITLE
issue: 4072930 Secrets Scanner - rename Jenkins secrets IDs 

### PR DESCRIPTION
**Pull request by vialogi**
## Description
Secrets Scanner - rename Jenkins secrets IDs to human-readable format

##### What
Update Jenkins's secrets reference in CI

##### Why ?
UUID format in secrets references confuses Secrets Scanner, which takes these data for passwords and fail.

## Change type
What kind of change does this PR introduce?
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes
- [ ] Documentation content changes
- [ ] Tests
- [ ] Other

## Check list
- [ ] Code follows the style de facto guidelines of this project
- [ ] Comments have been inserted in hard to understand places
- [ ] Documentation has been updated (if necessary)
- [ ] Test has been added (if possible)

### CODE REVIEW

**Comment by vialogi** [comment]
bot:retest

**Comment by vialogi** [comment]
bot:retest

**Comment by vialogi** [comment]
bot:retest

**Comment by vialogi** [comment]
bot:retest

**Comment by vialogi** [comment]
Run in a release mode on PDC Jenkins instance: https://nbupdc.blsm.nvidia.com/swx-media-master/job/libvma/job/LibVMA-release-dr/1/

**Review by dpressle — APPROVED** [review]

**Pull request merged**
