### PR TITLE
issue: 1026574 Fix PRM checksum check on pre OFED 3.3 versions

### PR DESCRIPTION
**Pull request by DanielLibenson**
Signed-off-by: Daniel Libenson <daneilli@mellanox.com>

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/1661/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1099/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/1665/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1103/ for details (Mellanox internal link).

**Comment by ilansmith** [comment]
Merged #359

**Pull request closed without merging**
