### PR TITLE
issue: 1041931 Fix for multicast source filtering regression

### PR DESCRIPTION
**Pull request by olgk**
There were two issues introduced by refactoring of packet
inspection:

1. Socket can exclude m_multicast status only after final source
address was excluded from the group.

2. We need to reconfigure rx_packet_processor after any dynamic
changes by sockopt.

Signed-off-by: Oleg Kuporosov <olegk@mellanox.com>

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/1782/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1230/ for details (Mellanox internal link).

**Comment by olgk** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/1784/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1232/ for details (Mellanox internal link).

**Comment by olgk** [comment]
It was merged

**Pull request closed without merging**
