### PR TITLE
issue: 770746 Extend jenkins check

### PR DESCRIPTION
**Pull request by igor-ivanov**
This commit enable compiler, valgrind and test units

@Di0gen could you look at.
tap-files can be found at $WORKSPACE/jenkins folder

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/35/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/36/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/37/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/38/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/39/ for details (Mellanox internal link).

**Comment by Di0gen** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/46/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/47/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/48/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/49/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/50/ for details (Mellanox internal link).

**Comment by miked-mellanox** [comment]
``` shell
21:38:52 make[3]: Entering directory `/scrap/jenkins/scrap/workspace/accl-libvma-pr/label/hpc-test-node/jenkins/compiler/0/src/vlogger'
21:38:52   CXX      vlogger.lo
21:38:52   CXX      main.o
21:38:53 In file included from /scrap/jenkins/scrap/workspace/accl-libvma-pr/label/hpc-test-node/src/vma/util/sys_vars.h(44),
21:38:53                  from /scrap/jenkins/scrap/workspace/accl-libvma-pr/label/hpc-test-node/src/vlogger/vlogger.cpp(47):
21:38:53 /scrap/jenkins/scrap/workspace/accl-libvma-pr/label/hpc-test-node/src/vma/util/verbs_extra.h(273): error: expression must have pointer-to-class type
21:38:53   		attr->flags = IBV_EXP_CQ_TIMESTAMP;
21:38:53   		^
21:38:53 
21:38:53 In file included from /scrap/jenkins/scrap/workspace/accl-libvma-pr/label/hpc-test-node/src/vma/util/sys_vars.h(44),
21:38:53                  from /scrap/jenkins/scrap/workspace/accl-libvma-pr/label/hpc-test-node/src/vlogger/vlogger.cpp(47):
21:38:53 /scrap/jenkins/scrap/workspace/accl-libvma-pr/label/hpc-test-node/src/vma/util/verbs_extra.h(274): error: expression must have pointer-to-class type
21:38:53   		attr->comp_mask = IBV_EXP_CQ_INIT_ATTR_FLAGS;
21:38:53   		^
21:38:53 
21:38:53 compilation aborted for /scrap/jenkins/scrap/workspace/accl-libvma-pr/label/hpc-test-node/src/vlogger/vlogger.cpp (code 2)
21:38:53 make[3]: *** [vlogger.lo] Error 1
21:38:53 make[3]: Leaving directory `/scrap/jenkins/scrap/workspace/accl-libvma-pr/label/hpc-test-node/jenkins/compiler/0/src/vlogger'
21:38:53 make[2]: *** [all-recursive] Error 1
21:38:53 make[2]: Leaving directory `/scrap/jenkins/scrap/workspace/accl-libvma-pr/label/hpc-test-node/jenkins/compiler/0/src'
21:38:53 make[1]: *** [all-recursive] Error 1
21:38:53 make[1]: Leaving directory `/scrap/jenkins/scrap/workspace/accl-libvma-pr/label/hpc-test-node/jenkins/compiler/0'
21:38:53 
make: *** [all] Error 2

```

**Comment by igor-ivanov** [comment]
@miked-mellanox It is fixed in other PR https://github.com/Mellanox/libvma/pull/63

**Comment by igor-ivanov** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/58/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by igor-ivanov** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/83/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/84/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/85/ for details (Mellanox internal link).

**Comment by miked-mellanox** [comment]
:+1:

**Pull request merged**
