### PR TITLE
issue: 885183 Enable vma_poll() usage mode by default

### PR DESCRIPTION
**Pull request by igor-ivanov**
There is race condition possibility in current implementation
related switching from legacy to vma_poll modes and back.
As far as this implementation is oriented to vma_poll mode
only we can set this mode by default.

See:
master: https://github.com/Mellanox/libvma/pull/101

@alexvm @OphirMunk please look at and pay attention on note.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/562/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/569/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/563/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/570/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/571/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/564/ for details (Mellanox internal link).

**Comment by OphirMunk** [comment]
Merged #232

**Pull request closed without merging**
