### PR TITLE
issue: 848172 Fix csbuild report errors in neighbor handling

### PR DESCRIPTION
**Pull request by liranoz12**
(CLANG_WARNING) warning: Use of memory after it is freed

Signed-off-by: Liran Oz <lirano@mellanox.com>

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/411/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/425/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/412/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/426/ for details (Mellanox internal link).

**Comment by liranoz12** [comment]
@OphirMunk, the error is not related to me.
```
16:36:27 configure.ac:28: error: possibly undefined macro: AC_PROG_LIBTOOL
16:36:27       If this token and others are legitimate, please use m4_pattern_allow.
16:36:27       See the Autoconf documentation.
```

**Comment by liranoz12** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/415/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/429/ for details (Mellanox internal link).

**Comment by OphirMunk** [comment]
:+1:

**Pull request merged**
