### PR TITLE
issue: 786406 Make coverity check stronger

### PR DESCRIPTION
**Pull request by igor-ivanov**
Added additional option for analyzes:
--enable-fnptr --fnptr-models - follows function pointers (by default it doesn't)
--all - add some checkers
--paths - increases number of paths checked (default is 5k, it increase cov run duration)

Signed-off-by: Igor Ivanov <igor.ivanov.va@gmail.com>

New options enable new issues that should be resolved in separate PR.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-redmine-issue/64/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/181/ for details (Mellanox internal link).

**Comment by Di0gen** [comment]
bot:retest

**Comment by OphirMunk** [comment]
@igor-ivanov Please indicate by how much time cov run duration increases following this PR

**Comment by igor-ivanov** [comment]
Using additional parameters adds 1-2mins for analysis.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/171/ for details (Mellanox internal link).

**Comment by Di0gen** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-redmine-issue/73/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/175/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/190/ for details (Mellanox internal link).

**Comment by igor-ivanov** [comment]
this PR should be applied after https://github.com/Mellanox/libvma/pull/133

**Comment by rosenbaumalex** [comment]
+1

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/218/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/231/ for details (Mellanox internal link).

**Pull request merged**
