### PR TITLE
issue 797814: Avoid double deletion of timer handler

### PR DESCRIPTION
**Pull request by OphirMunk**
Signed-off-by: Ophir Munk ophirmu@mellanox.com

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-redmine-issue/36/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/153/ for details (Mellanox internal link).

**Comment by NirNitzani** [comment]
bot:retest

**Comment by liranoz12** [comment]
this is a workaround and not a real fix.

**Pull request closed without merging**
