### PR TITLE
issue: 1469556 Add sendfile support

### PR DESCRIPTION
**Pull request by liranoz12**
Signed-off-by: Liran Oz <lirano@mellanox.com>

### CODE REVIEW

**Comment by liranoz12** [comment]
@igor-ivanov @serglelv  please review

**Comment by serglelv** [comment]
The original linux sendfile was not designed to support a large file. The glibc sendfile() wrapper function transparently deals with sendfile/sendfile64.  It seems vma should support sendfile64() as well.

**Comment by serglelv** [comment]
It seems GET_ORIG_FUNC(sendfile64); should be added.

**Comment by liranoz12** [comment]
Updated @serglelv

**Comment by serglelv** [comment]
bot:restest

**Comment by liranoz12** [comment]
bot:retest

**Comment by liranoz12** [comment]
bot:retest

**Pull request merged**
