### PR TITLE
issue 781492: Add testbed application

### PR DESCRIPTION
**Pull request by igor-ivanov**
Description:

- This application includes sender, engine, receiver units.
- sender and receiver are located on the same node when engine on another.
- Each connection in sender program constantly sends messages to engine
program at a specific message rate.
- The engine redirects received messages to the connections with receiver process.

@alexvm please review

### CODE REVIEW

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/93/ for details (Mellanox internal link).

**Comment by rosenbaumalex** [comment]
+1

**Comment by miked-mellanox** [comment]
@igor-ivanov , @rosenbaumalex - does it make sense to call it from jenkins?

**Comment by rosenbaumalex** [comment]
We should not push this test now. We should start some basic tests and plan this coverage.

1. We don't have a defined automatic pass criteria
2. It is still not stable - WIP

**Comment by igor-ivanov** [comment]
@miked-mellanox I agree with @rosenbaumalex. This test is very specific

**Pull request merged**
