### PR TITLE
Revert "issue: 763018 Search neigh table using both dst addr and ifin…

### PR DESCRIPTION
**Pull request by OphirMunk**
…dex"

This reverts commit ea4eae44da07959642cb97a1e71ee87dc9f73573.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/75/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/76/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/77/ for details (Mellanox internal link).

**Comment by OphirMunk** [comment]
jenkins: no_cov
bot:retest

**Comment by OphirMunk** [comment]
jenkins: nocov
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/78/ for details (Mellanox internal link).

**Comment by OphirMunk** [comment]
Was a try to detect Coverity failures

**Pull request closed without merging**
