### PR TITLE
Pr rpm/release 8.2.1

### PR DESCRIPTION
**Pull request by serglelv**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/1396/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/927/ for details (Mellanox internal link).

**Comment by OphirMunk** [comment]
@serglelv Please explain this PR.

**Comment by serglelv** [comment]
It is for YUM RPM repository test PR. It seems it is a problem with configuration and currently disabled. The PR was closed and should be deleted.  @OphirMunk

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/1402/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/933/ for details (Mellanox internal link).

**Pull request closed without merging**
