### PR TITLE
issue: 865589 Wrong errno EBUSY on success fixed.

### PR DESCRIPTION
**Pull request by serglelv**
Wrong errno code EBUSY on success was fixed. Please review. 
Signed-off-by: sergeyly <sergeyly@mellanox.com>
@igor-ivanov @OphirMunk

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/721/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/726/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/753/ for details (Mellanox internal link).

**Comment by igor-ivanov** [comment]
After talk with @serglelv we agreed that there is no special requirements for setting errno to zero for all library functions.
In most cases there are following rules:
- user should assign zero to errno before function call if he needs to check success/failure
- errno value is unspecified after successful function call
- errno can be valuable after failed function call
see good article about it https://www.securecoding.cert.org/confluence/pages/viewpage.action?pageId=6619179

**Comment by OphirMunk** [comment]
@serglelv - is this PR can be closed?

**Comment by OphirMunk** [comment]
PR closed based on latest comments

**Pull request closed without merging**
