### PR TITLE
issue: 764913 Adapt vma_stats -v 5 PID column to netstat related one

### PR DESCRIPTION
**Pull request by igor-ivanov**
This change replace 'PID' column title of vma_stats -v5 output with
'PID/Program name' changing column data accordingly.

Signed-off-by: Igor Ivanov <igor.ivanov.va@gmail.com>

@rosenbaumalex @OphirMunk please review and accept if no issue is observed

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/14/ for details (Mellanox internal link).

**Comment by rosenbaumalex** [comment]
+1

**Comment by OphirMunk** [comment]
PR accepted

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/17/ for details (Mellanox internal link).

**Pull request closed without merging**
