### PR TITLE
issue: 925571 Add textual vma spec support and new latency spec

### PR DESCRIPTION
**Pull request by DanielLibenson**
Added textual support for VMA_SPEC parameter
	* VMA_SPEC=10 is now VMA_SPEC=ultra-latency.
	* Numeric parameters are still supported
	Added new latency spec [VMA_SPEC=latency]

Signed-off-by: Daniel Libenson <daneilli@mellanox.com>

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/708/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/705/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/709/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/711/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/715/ for details (Mellanox internal link).

**Comment by OphirMunk** [comment]
Merged #266

**Pull request closed without merging**
