### PR TITLE
issue: 847360 update github's README.md file

### PR DESCRIPTION
**Pull request by rosenbaumalex**
Signed-off-by: Alex Rosenbaum <Alexr@mellanox.com>

### CODE REVIEW

**Comment by rosenbaumalex** [comment]
You can see 'demo' of how this looks here: https://github.com/rosenbaumalex/libvma/tree/issue_847360_updaet_githubs_README_md_file#introduction

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/369/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/387/ for details (Mellanox internal link).

**Comment by rosenbaumalex** [comment]
this PR will be replaced with https://github.com/Mellanox/libvma/pull/181
closing this one

**Pull request closed without merging**
