### PR TITLE
issue: 1089826 add stats to Multi Packet ring

### PR DESCRIPTION
**Pull request by rafiw**
This PR adds basic ring and cq stats to mp_rq feature
Signed-off-by: Rafi Wiener <rafiw@mellanox.com>

### CODE REVIEW

**Comment by rafiw** [comment]
======================================================
        Fd=[22]
- UDP, Non-blocked, MC Loop Enabled
- Local Address   = [224.1.1.1:2000]
- Member of = [224.1.1.1]
Rx and Tx where not active
======================================================
        CQ=[0]
Packets dropped:              0
Packets queue len:            0
Drained max:               1023
Buffer pool size:        131072
======================================================
======================================================
        RING=[0]
Packets count:          2312400
Packets bytes:       3334480800
Interrupt requests:           0
Interrupt received:           0
Moderation frame count:         48
Moderation usec period:         50
Retransmissions:              0
======================================================
======================================================
        BUFFER_POOL(RX)=[0]
Size:                    200000
No buffers error:             0
======================================================
        BUFFER_POOL(TX)=[1]
Size:                    199744
No buffers error:             0
======================================================

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1554/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1556/ for details (Mellanox internal link).

**Comment by rafiw** [comment]
rebased

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1584/ for details (Mellanox internal link).

**Comment by liranoz12** [comment]
Merged #438.

**Pull request closed without merging**
