### PR TITLE
issue: 3336161 Adding COPYING license file

### PR DESCRIPTION
**Pull request by AlexanderGrissik**
Signed-off-by: Alexander Grissik <agrissik@nvidia.com>

## Description
Adding COPYING file for license

##### What
Missing file

##### Why ?
Licensing

## Change type
What kind of change does this PR introduce?
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Tests
- [X] Other

## Check list
- [ ] Code follows the style de facto guidelines of this project
- [ ] Comments have been inserted in hard to understand places
- [ ] Documentation has been updated (if necessary)
- [ ] Test has been added (if possible)

### CODE REVIEW

**Review by iftahl — APPROVED** [review]

**Comment by iftahl** [comment]
chatgpt approved spelling and grammer =]

**Comment by AlexanderGrissik** [comment]
bot:retest

**Comment by AlexanderGrissik** [comment]
bot:retest

**Comment by AlexanderGrissik** [comment]
bot:retest

**Comment by AlexanderGrissik** [comment]
Last CI run has Blackduck system failure caused by general Blackduck instability. Pushing as it passed with previous CI run.

**Pull request merged**
