### PR TITLE
issue: 793030 Fix rpm rebuild failure

### PR DESCRIPTION
**Pull request by igor-ivanov**
This change fixes rpmbuild --rebuild failure.

Signed-off-by: Igor Ivanov <igor.ivanov.va@gmail.com>

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-redmine-issue/29/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/146/ for details (Mellanox internal link).

**Comment by igor-ivanov** [comment]
@OphirMunk can we merge it?

**Comment by igor-ivanov** [comment]
it was verified on test infrastructure successfully.

**Pull request merged**
