### PR TITLE
issue: 820855 explicitly set QP capability of max send SG to 2 (workaround for CX4/Upstream OFED)

### PR DESCRIPTION
**Pull request by OphirMunk**
Signed-off-by: Alex Rosenbaum <Alexr@mellanox.com>

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/178/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/194/ for details (Mellanox internal link).

**Comment by rosenbaumalex** [comment]
Code looks good.
But need to update commit message since this is not a "workaround". please remove the "(workaround for CX4/Upstream OFED)"

I suggest we use the new define MCE_DEFAULT_TX_NUM_SGE in: [dst_entry.h#L110](https://github.com/Mellanox/libvma/blob/master/src/vma/proto/dst_entry.h#L110): "ibv_sge m_sge[2]"

**Comment by rosenbaumalex** [comment]
suggested commit message updates:
"issue: 820855 explicitly set QP init attr cap of max send SG to 2

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/180/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/196/ for details (Mellanox internal link).

**Comment by miked-mellanox** [comment]
``` shell
10:56:07 Mellanox SOCKPERF Verification Tool v0.1.
10:56:07 **********************************
10:56:07 * Options: -a /scrap/jenkins/scrap/workspace/accl-libvma-pr/label/hpc-test-node/jenkins/test/sockperf/install/bin/sockperf -x  --load-vma=/scrap/jenkins/scrap/workspace/accl-libvma-pr/label/hpc-test-node/jenkins/install/lib/libvma.so  -t tcp-pp:tc[1-9]$ -s 2.11.0.12 -l /scrap/jenkins/scrap/workspace/accl-libvma-pr/label/hpc-test-node/jenkins/test/eth-tcp-pp.log -e  VMA_TX_BUFS=20000 VMA_RX_BUFS=20000  --progress=0
10:56:07 * Log file: /scrap/jenkins/scrap/workspace/accl-libvma-pr/label/hpc-test-node/jenkins/test/eth-tcp-pp.log
10:56:07 * Dump file: eth-tcp-pp.dump
10:56:07 * Host: hpc-test-node
10:56:07 * Target: 2.11.0.12
10:56:07 * Output level: 2
10:56:07 * Log level: 3
10:56:07 **********************************
10:56:07 
10:56:16 FAIL   tcp-pp       tc1          #1 - ping-pong w/o arguments
10:56:25 FAIL   tcp-pp       tc2          #2 - ping-pong option --dontwarmup
10:56:35 FAIL   tcp-pp       tc3          #3 - ping-pong option -b10
10:56:44 FAIL   tcp-pp       tc4          #4 - ping-pong option -b100
10:56:54 FAIL   tcp-pp       tc5          #5 - ping-pong option -b1000
10:57:12 FAIL   tcp-pp       tc6          #6 - ping-pong option -t10
10:57:52 FAIL   tcp-pp       tc7          #7 - ping-pong option -t30
10:58:01 FAIL   tcp-pp       tc8          #8 - ping-pong option -m32
10:58:10 FAIL   tcp-pp       tc9          #9 - ping-pong option -m4096
10:58:10 
10:58:10 **********************************
10:58:10 * Passed: 0
10:58:10 * Failed: 9
10:58:10 * Total: 9
10:58:10 * Start time: 05-07-2016 10:56:07
10:58:10 * Finish time: 05-07-2016 10:58:10
10:58:10 * Duration: 0:02:03
```

**Comment by rosenbaumalex** [comment]
Need to check what is wrong with internal test server. There were some power issues in last few days.

@miked-mellanox all these test pass on DMZ test node.

10:52:34 Mellanox SOCKPERF Verification Tool v0.1.
10:52:34 **********************************
10:52:34 * Options: -a /tmp/workspace/accl-libvma-pr/label/dmz-hail17/jenkins/test/sockperf/install/bin/sockperf -x  --load-vma=/tmp/workspace/accl-libvma-pr/label/dmz-hail17/jenkins/install/lib/libvma.so  -t tcp-pp:tc[1-9]$ -s 172.21.1.1 -l /tmp/workspace/accl-libvma-pr/label/dmz-hail17/jenkins/test/eth-tcp-pp.log -e  VMA_TX_BUFS=20000 VMA_RX_BUFS=20000  --progress=0
10:52:34 * Log file: /tmp/workspace/accl-libvma-pr/label/dmz-hail17/jenkins/test/eth-tcp-pp.log
10:52:34 * Dump file: eth-tcp-pp.dump
10:52:34 * Host: r-aa-hail17
10:52:34 * Target: 172.21.1.1
10:52:34 * Output level: 2
10:52:34 * Log level: 3
10:52:34 **********************************
10:52:34 
10:52:43 PASS   tcp-pp       tc1          #1 - ping-pong w/o arguments
10:52:53 PASS   tcp-pp       tc2          #2 - ping-pong option --dontwarmup
10:53:02 PASS   tcp-pp       tc3          #3 - ping-pong option -b10
10:53:11 PASS   tcp-pp       tc4          #4 - ping-pong option -b100
10:53:21 PASS   tcp-pp       tc5          #5 - ping-pong option -b1000
10:53:39 PASS   tcp-pp       tc6          #6 - ping-pong option -t10
10:54:19 PASS   tcp-pp       tc7          #7 - ping-pong option -t30
10:54:28 PASS   tcp-pp       tc8          #8 - ping-pong option -m32
10:54:37 PASS   tcp-pp       tc9          #9 - ping-pong option -m4096
10:54:37 
10:54:37 **********************************
10:54:37 * Passed: 9
10:54:37 * Failed: 0
10:54:37 * Total: 9
10:54:37 * Start time: 05-07-2016 07:52:29
10:54:37 * Finish time: 05-07-2016 07:54:31
10:54:37 * Duration: 0:02:02
10:54:37 **********************************

**Comment by miked-mellanox** [comment]
thanks. please sort it with @Di0gen to avoid false alarms.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/184/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/200/ for details (Mellanox internal link).

**Comment by rosenbaumalex** [comment]
+1

**Pull request merged**
