### PR TITLE
Fix advanced route issues

### PR DESCRIPTION
**Pull request by ashanably**

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/609/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/608/ for details (Mellanox internal link).

**Comment by OphirMunk** [comment]
PR newly submitted in master branch. Will close this one

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/611/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/612/ for details (Mellanox internal link).

**Pull request closed without merging**
