### PR TITLE
issue: 1073223 Enable Debian package timestamp

### PR DESCRIPTION
**Pull request by serglelv**
The timestamp enabled in the debian/changelog file

Signed-off-by: Sergey Lykov <sergeyly@mellanox.com>

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1628/ for details (Mellanox internal link).

**Comment by serglelv** [comment]
Please review. 
@igor-ivanov

**Comment by serglelv** [comment]
@igor-ivanov  Your approach is okay for the current debian packages support but can be extended with the external script if the extended changelog will be needed.

**Comment by serglelv** [comment]
Updated. Please review.
@igor-ivanov

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1632/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1633/ for details (Mellanox internal link).

**Comment by rafiw** [comment]
consider removing ork from other places as well
[rafiw@r-aa-apollo02 vma]$ grep ork@mellanox.com -R *
build/build_git_rpm_deb_mellanox_internal.sh:#EMAIL="ork@mellanox.com" # for debug
build/build_git_rpm_deb_mellanox_internal.sh:        debUserEmail="ork@mellanox.com"
debian/changelog.in: -- Or Kehati <ork@mellanox.com>  Wed, 21 Oct 2015 12:03:19 +0200
debian/control:Maintainer: Or Kehati <ork@mellanox.com>
debian/changelog: -- Or Kehati <ork@mellanox.com>  Wed, 21 Oct 2015 12:03:19 +0200

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1638/ for details (Mellanox internal link).

**Comment by rafiw** [comment]
@serglelv @liranoz12 @ilansmith maybe we should use a more generic email e.g. support@mellanox.com

**Comment by serglelv** [comment]
@rafiw @liranoz12 @ilansmith  At least one human with their personal email address should be used. Debian policy/Chapter 3. Binary packages/3.3. The maintainer of a package

**Comment by rafiw** [comment]
ok

**Comment by liranoz12** [comment]
Merged #457

**Pull request closed without merging**
