### PR TITLE
issue: 1063164 Update License date

### PR DESCRIPTION
**Pull request by serglelv**
Signed-off-by: Sergey Lykov <sergeyly@mellanox.com>

### CODE REVIEW

**Comment by serglelv** [comment]
Please review.
@OphirMunk

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1459/ for details (Mellanox internal link).

**Comment by serglelv** [comment]
Please review.
@liranoz12

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1464/ for details (Mellanox internal link).

**Comment by serglelv** [comment]
Updated. Please review.
@OphirMunk @liranoz12

**Comment by liranoz12** [comment]
:+1:

**Comment by OphirMunk** [comment]
:+1:

**Comment by OphirMunk** [comment]
Merged #428

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/1466/ for details (Mellanox internal link).

**Pull request closed without merging**
