### PR TITLE
issue: 770746 Update jenkins from master

### PR DESCRIPTION
**Pull request by igor-ivanov**
see related in master 
https://github.com/Mellanox/libvma/commit/a96249
https://github.com/Mellanox/libvma/commit/f39afa0
https://github.com/Mellanox/libvma/commit/f4ddf05
https://github.com/Mellanox/libvma/commit/312e53

### CODE REVIEW

**Comment by mellanox-github** [comment]
Can one of the admins verify this patch?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/91/ for details (Mellanox internal link).

**Comment by OphirMunk** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/92/ for details (Mellanox internal link).

**Comment by miked-mellanox** [comment]
seems compilation issue, maybe unsupported mofed?
```
23:49:44 /scrap/jenkins/workspace/accl-libvma-pr/label/clx-ppc-04.mtl.labs.mlnx/src/vma/dev/qp_mgr.cpp: In member function 'void qp_mgr::mlx5_send(vma_ibv_send_wr*)':
23:49:44 /scrap/jenkins/workspace/accl-libvma-pr/label/clx-ppc-04.mtl.labs.mlnx/src/vma/util/asm-ppc64.h:21:9: error: cannot convert 'volatile mlx5_wqe64' to 'volatile uintptr_t {aka volatile long unsigned int}' in assignment
23:49:44   *dst++ = *src++; \
23:49:44          ^
23:49:44 /scrap/jenkins/workspace/accl-libvma-pr/label/clx-ppc-04.mtl.labs.mlnx/src/vma/dev/qp_mgr.cpp:530:2: note: in expansion of macro 'COPY_64B_NT'
23:49:44   COPY_64B_NT(dst, m_sq_hot_wqe);
23:49:44   ^
23:49:44 /scrap/jenkins/workspace/accl-libvma-pr/label/clx-ppc-04.mtl.labs.mlnx/src/vma/util/asm-ppc64.h:22:9: error: cannot convert 'volatile mlx5_wqe64' to 'volatile uintptr_t {aka volatile long unsigned int}' in assignment
23:49:44   *dst++ = *src++; \
23:49:44          ^
```

**Comment by OphirMunk** [comment]
@igor-ivanov can you fix errors or indicate root cause? Why is error unique to experimental_256B branch (tests pass OK on master branch).

**Comment by OphirMunk** [comment]
@igor-ivanov you have gathered 3 different commits/issues under one PR. Please close this PR and issue 3 different PRs - 1 for each commit You can use the same issue number 770746 (and same log message) for each commit

**Comment by igor-ivanov** [comment]
@OphirMunk all these commits relate jenkins. I can squash them in one if it is required.

**Comment by OphirMunk** [comment]
@igor-ivanov No need. Squashing is automatically done by "Merge method request".

**Comment by igor-ivanov** [comment]
experimental branch supports latest MOFED only.
Most failures relate previous MOFED.
r-vmb-sles11-sp3-x86-64 : MLNX_OFED_LINUX-2.0-3.0.0
r-vmb-rhel6-u5-x86-64 : MLNX_OFED_LINUX-2.3-1.5.4
etc

**Comment by miked-mellanox** [comment]
@igor-ivanov - thanks
is there way to detect unsupported mofed during configure and exit gracefully?

**Comment by igor-ivanov** [comment]
@miked-mellanox I think it could be done but result will be failure on configure in any case.

**Comment by OphirMunk** [comment]
@igor-ivanov:
1. experimental_256B branch is only applicable to ConnectX-4 interfaces. Please consider running Jenkins interface tests on those HCA types only.
2. Is there a way of detecting MOFED version and exit before running configure at all?

**Comment by igor-ivanov** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-redmine-issue/39/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/156/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-redmine-issue/40/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/157/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-redmine-issue/41/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/158/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-redmine-issue/42/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/159/ for details (Mellanox internal link).

**Comment by igor-ivanov** [comment]
let look at compilation issue before merge

**Comment by igor-ivanov** [comment]
MOFED 3.3-1 has structures defined in src/vma/hw/mlx5/wqe.h
I see following ways to resolve compilation issues:
- check required types in configure.ac (it allows to use MOFED 3.2+ but not good for pushing to master)
- remove src/vma/hw/mlx5/wqe.h and use MOFED 3.3-1+ (more suitable for master)

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-redmine-issue/46/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/163/ for details (Mellanox internal link).

**Comment by igor-ivanov** [comment]
experimental_256B branch supports MOFED-3.2 only at the moment. So jenkins is launched on the specific MOFED now.
@OphirMunk this PR can be merged

**Comment by Di0gen** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-redmine-issue/47/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/164/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/accl-libvma-pr/164/ for details (Mellanox internal link).

**Comment by OphirMunk** [comment]
@alexvm - PR will be merged soon. Do you have any comments?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-redmine-issue/54/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/accl-libvma-pr/171/ for details (Mellanox internal link).

**Comment by OphirMunk** [comment]
All commits accepted and merged

**Pull request merged**
